export const modulesArray = [
  {
    moduleNumber: 1,
    moduleTitle: 'Название первого модуля',
    moduleIsActive: true,
    moduleIsAvailable: true,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 1-1',
        lessonBody: 'Крутой урок первого модуля',
        lessonIsActive: true,
        lessonIsAvailable: true,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 1-2',
        lessonBody: 'Новый урок первого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 1-3',
        lessonBody: 'Настоящий урок первого модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
  {
    moduleNumber: 2,
    moduleTitle: 'Хорошее название модуля',
    moduleIsActive: false,
    moduleIsAvailable: false,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 2-1',
        lessonBody: 'Крутой урок второго модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 2-2',
        lessonBody: 'Новый урок второго модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 2-3',
        lessonBody: 'Настоящий урок второго модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
  {
    moduleNumber: 3,
    moduleTitle: 'Великолепное название модуля',
    moduleIsActive: false,
    moduleIsAvailable: false,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 3-1',
        lessonBody: 'Крутой урок третьего модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 3-2',
        lessonBody: 'Новый урок третьего модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 3-3',
        lessonBody: 'Настоящий урок третьего модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
  {
    moduleNumber: 4,
    moduleTitle: 'Ещё один прекрасный модуль',
    moduleIsActive: false,
    moduleIsAvailable: false,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 4-1',
        lessonBody: 'Крутой урок четвертого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 4-2',
        lessonBody: 'Новый урок четвертого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 4-3',
        lessonBody: 'Настоящий урок четвертого модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
  {
    moduleNumber: 5,
    moduleTitle: 'Модуль - чемпион!',
    moduleIsActive: false,
    moduleIsAvailable: false,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 5-1',
        lessonBody: 'Крутой урок пятого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 5-2',
        lessonBody: 'Новый урок пятого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 5-3',
        lessonBody: 'Настоящий урок пятого модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
  {
    moduleNumber: 6,
    moduleTitle: 'Крутой модуль',
    moduleIsActive: false,
    moduleIsAvailable: false,
    lessons: [
      {
        lessonNumber: 1,
        lessonTitle: 'Урок 6-1',
        lessonBody: 'Крутой урок шестого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,

        lessonIsCompleted: false,
      },
      {
        lessonNumber: 2,
        lessonTitle: 'Урок 6-2',
        lessonBody: 'Новый урок шестого модуля',
        lessonIsActive: false,
        lessonIsAvailable: false,

        lessonIsCompleted: false,
      },
      {
        lessonNumber: 3,
        lessonTitle: 'Урок 6-3',
        lessonBody: 'Настоящий урок шестого модуля!',
        lessonIsActive: false,
        lessonIsAvailable: false,
        lessonIsCompleted: false,
      },
    ],
  },
]
